# Generated by Django 3.2 on 2022-11-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='zipcode',
            field=models.IntegerField(blank=True),
        ),
    ]
