# Generated by Django 3.2 on 2022-11-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruh', '0002_alter_visitor_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=150)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField(max_length=3000)),
                ('when_sent', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='visitor',
            name='when_visited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
