# Generated by Django 4.1.2 on 2022-11-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruh', '0003_auto_20221125_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
